### ISSUE TITLE
Hour Editor 

### ISSUE THREAD

**Issue by sccoache** [SoftEngTeamC/FaulknerMap2#49]
- [x] There is no limit on the size of input for the entry fields on the hour editor

- [x] On invalid format error resets all text fields

- [x] No indication of a successful change

- [x] Can't press help until hours have been changed

- [x] Can enter invalid format
If you go to the hour's editor and enter a time such as 9:1 (so without a second digit) the format is accepted and will print times as 9:1 am - 5:00 pm for example

- [x] Time can be set to be equal
You can set visiting ours to be from 5:00 am - 5:00 am

- [x] Doesn't confirm if AM or PM has been entered
If you input a time such as 9:00 if will default to AM or PM, not sure if this is a bug or on purpose

- [x] Changing the hours in the Hours Editor automatically brings you back to the main screen without any confirmation if successful

- [x] The main page for Hours Editor has a type, the title is "Hours visitor Editor" so "visitor" should be capitalized 

(This was also just a test for me to see how the issues tab works, I'll compile more bugs next time before making a post)

**Comment by atags22** [comment]
[https://github.com/SoftEngTeamC/FaulknerMap2/commit/bf1ca9dcfdb11f59759f3d7623a6cc195d6c5ea1](url)

**Comment by atags22** [comment]
[https://github.com/SoftEngTeamC/FaulknerMap2/commit/3f30230becf745795ddf90212cd6d48411b75f71](url)

**Comment by atags22** [comment]
All better! Closed by multiple commits.
