### ISSUE TITLE
Admin Login

### ISSUE THREAD

**Issue by sccoache** [SoftEngTeamC/FaulknerMap2#60]
- [x] If entered incorrectly three times brings you back to the main page, maybe show a count or a confirmation before booting the user back to the main page

**Comment by droydstix** [comment]
Try now?

**Comment by sccoache** [comment]
It works but "Attempts:" is spelled wrong, and maybe a countdown or making it 1/3 then 2/3 so they know the number of attempts? It's not really a bug and I am looking for those too I just figured I would mention it. That being said there are no bugs.

**Comment by sccoache** [comment]
So far
