### ISSUE TITLE
Text Directions

### ISSUE THREAD

**Issue by sccoache** [SoftEngTeamC/FaulknerMap2#62]
Double display of elevator paths

Example Case:
Selecting user Laura Andromalos as the start
Selecting user Samuel Ash as the destination
Text Directions displays the following: (The issue is in bold)

Move straight 4.5 feet, then take a slight right turn
Move straight 24.4 feet, then take a left turn
Move straight 22.1 feet, then take a slight right turn
**Take elevator to floor: 1**
**Take elevator to floor: 4**
Move straight 47.6 feet, then take a right turn
Move forward 4.9 feet. You have arrived.

**Comment by atags22** [comment]
All better now! Sending back to QA for verification.
